# Site settings
title: Infection Detected
description: A platform for security engineer, Threat Hunter, and CTF player to share their knowledge and experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title/

# Pagination
paginate: 6
paginate_path: "/page/:num"

# Author Settings
author:
  name: Shubhendu
  avatar: /assets/images/authors/shubhendu.jpg

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

collections:
  posts:
    output: true
  tags:
    output: true
    permalink: /tags/:name/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
  load_paths:
    - _sass
    - assets/css

# Jekyll Performance Optimizations
incremental: false  # Set to true for faster builds during development
strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true

# Assets
assets:
  sources:
    - assets/css
    - assets/images
    - assets/js

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
  - docs/
  - "*.sh"
  - .nvmrc
  - .ruby-version
  - .gitignore
  - .github/

# Defaults
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: Shubhendu
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Google Analytics
google_analytics: "G-QG3ERH50HG" # Replace this with your GA4 measurement ID
